-- ════════════════════════════════════════════════════════════════
--  答案之书 · 数据表
--  用法：Supabase 控制台 → 左侧 SQL Editor → New query → 整段粘贴 → Run
--  可重复执行，不会报错、不会清掉已有数据。
-- ════════════════════════════════════════════════════════════════

create table if not exists public.readings (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  category      text        not null,          -- 用户选的方向：爱情 / 事业 / 健康 / 学业 / 整体运势
  question      text        not null,          -- 用户输入的问题原文
  answer_text   text        not null,          -- 抽中的那句答案
  answer_index  integer,                       -- 0-999，答案在答案库里的序号
  page_number   integer,                       -- 换算出来的页码
  user_agent    text,                          -- 浏览器 UA，方便你看设备分布
  referrer      text,                          -- 从哪来的
  constraint readings_question_len  check (char_length(question) between 1 and 2000),
  constraint readings_category_len  check (char_length(category) between 1 and 32)
);

create index if not exists readings_created_at_idx on public.readings (created_at desc);
create index if not exists readings_category_idx   on public.readings (category);

-- ── 权限：只准写，不准读 ──────────────────────────────────────
-- 前端用的是 anon key，这个 key 会公开在浏览器里。
-- 所以一定要开 RLS，并且只给 insert 权限：
--   * 陌生人拿到 anon key 也只能往表里塞记录，读不到任何人的问题
--   * 你自己在 Supabase Dashboard 的 Table Editor 用的是 service_role，
--     不受 RLS 限制，照样看得到全部数据

alter table public.readings enable row level security;

drop policy if exists "anon can insert readings" on public.readings;
create policy "anon can insert readings"
  on public.readings
  for insert
  to anon, authenticated
  with check (true);

-- 显式收口：anon / authenticated 不能读、改、删
revoke select, update, delete on table public.readings from anon, authenticated;
grant  insert on table public.readings to anon, authenticated;

-- 自增主键要用到序列
do $$
begin
  if exists (select 1 from pg_class where relname = 'readings_id_seq') then
    execute 'grant usage, select on sequence public.readings_id_seq to anon, authenticated';
  end if;
end $$;


-- ════════════════════════════════════════════════════════════════
--  可选：加一道防刷限制，防止有人拿脚本灌垃圾
--  下面这段默认注释掉，需要时把注释去掉再 Run
-- ════════════════════════════════════════════════════════════════
-- create or replace function public.readings_rate_limit()
-- returns trigger language plpgsql security definer as $$
-- begin
--   if (select count(*) from public.readings
--       where created_at > now() - interval '1 minute') > 120 then
--     raise exception '太频繁了，请稍后再试';
--   end if;
--   return new;
-- end $$;
--
-- drop trigger if exists readings_rate_limit on public.readings;
-- create trigger readings_rate_limit before insert on public.readings
--   for each row execute function public.readings_rate_limit();
